import {  OldProduct } from "./type";
// import phoneImage from "../../public/Home/image.png";
import phoneImage1 from "../../public/Home/ProductList/i14.png";
import phoneImage2 from "../../public/Home/ProductList/Samsung_Galaxy.png";
import phoneImage3 from "../../public/Home/ProductList/ipad_pro.png";
// import { Smartphone, Watch, Camera, Headphones, Monitor, Gamepad2 } from "lucide-react";
// export const categories: Category[] = [
//   { id: 1, name: "Phones", icon: Smartphone },
//   { id: 2, name: "SmartWatches", icon: Watch },
//   { id: 3, name: "Cameras", icon: Camera },
//   { id: 4, name: "Headphones", icon: Headphones },
//   { id: 5, name: "Computers", icon: Monitor },
//   { id: 6, name: "Gaming", icon: Gamepad2 },
// ];

// Add this above your return()
export const heroSlides = [
  {
    title: "iPhone 14 Pro",
    subtitle: "Pro.Beyond.",
    description:
      "Experience the power of the A16 Bionic chip, advanced camera system, and stunning Super Retina XDR display.",
    image:  phoneImage1,
    productId:1,
  },
  {
    title: "Samsung Galaxy S24 Ultra",
    subtitle: "Epic Innovation.",
    description:
      "Capture every detail with AI-powered photography and enjoy a smooth, premium performance.",
    image: phoneImage2,
    productId: 2,
  },
  {
    title: "Google Pixel 9 Pro",
    subtitle: "Pure Android.",
    description:
      "Powered by Google AI with an incredible camera and the cleanest Android experience.",
    image: phoneImage3,
    productId: 3,
  },
];
export const products: OldProduct[] = [
  {
    id: 1,
    name: "iPhone 14 Pro Max",
    description: "Apple iPhone 14 Pro Max 128GB Deep Purple ",
    price: 900,
    image: "/Home/ProductList/i14.png",
    category: "Phones",
    type: "New Arrivals",
    rating: 4,
    stock: 550,
    totalsold: 200,
    discount: 10,
    discountPrice: 810,
    company: "Apple",
    totalRevenue : 162000,
  },
  {
    id: 2,
    name: "Camera",
    description: "Blackmagic Pocket Cinema Camera 6k complete kit",
    price: 2000,
    image: "/Home/ProductList/camera.png",
    category: "Cameras",
    type: "Featured",
    rating: 4,
    stock: 600,
    totalsold: 200,
    discount: 70,
    discountPrice: 600,
    company: "Canon",
    totalRevenue : 200000,
  },
  {
    id: 3,
    name: "Apple Watch Series 9",
    description: "Apple Watch Series 9 GPS 41mm Starlight Aluminum Case ",
    price: 10000,
    image: "/Home/ProductList/apple_watch.png",
    category: "SmartWatches",
    type: "Bestsellers",
    rating: 4,
    stock: 750,
    totalsold: 200,
    discount: 60,
    discountPrice: 4000,
    company: "Apple",
    totalRevenue : 80000,
  },
  {
    id: 4,
    name: "AirPods Max",
    description: "Apple AirPods Max Over-Ear Headphones - Space Gray",
    price: 549,
    image: "/Home/ProductList/airpods.png",
    category: "Headphones",
    type: "New Arrivals",
    rating: 4,
    stock: 570,
    totalsold: 200,
    discount: 10,
    discountPrice: 494,
    company: "Apple",
    totalRevenue : 98800,
  },
  {
    id: 5,
    name: "Samsung Galaxy Watch6",
    description: "Samsung Galaxy Watch6 Classic 47mm Black",
    price: 900,
    image: "/Home/ProductList/watch.png",
    category: "SmartWatches",
    type: "New Arrivals",
    rating: 4,
    stock: 1000,
    totalsold: 200,
    discount: 10,
    discountPrice: 810,
    company: "Samsung",
    totalRevenue : 16200,
  },
  {
    id: 6,
    name: "Galaxy Buds FE",
    description: "Galaxy Buds FE Graphite  Earbuds with 3D Sound",
    price: 3000,
    image: "/Home/ProductList/buds.png",
    category: "Headphones",
    type: "Featured",
    rating: 4,
    stock: 570,
    totalsold: 200,
    discount: 50,
    discountPrice: 1500,
    company: "Samsung",
    totalRevenue : 300000,
  },
  {
    id: 7,
    name: "Galaxy Z Fold5 Unlocked",
    description: "Galaxy Z Fold5 Unlocked | 256GB | Phantom Black",
    price: 399,
    image: "/Home/ProductList/galaxyZ.png",
    category: "Phones",
    type: "Bestsellers",
    rating: 400,
    stock: 50,
    totalsold: 200,
    discount: 10,
    discountPrice: 359,
    company: "Samsung",
    totalRevenue : 71800,
  },
  {
    id: 8,
    name: "Apple iPad",
    description: "Apple iPad 9 10.2 64GB Wi-Fi Silver (MK2L3) 2021",
    price: 600,
    image: "/Home/ProductList/ipad.png",
    category: "Phones",
    type: "New Arrivals",
    rating: 4,
    stock: 450,
    totalsold: 200,
    discount: 50,
    discountPrice: 300,
    company: "Apple",
    totalRevenue : 120000,
  },
  {
    id: 9,
    name: "Apple iPad Pro",
    description: "Apple iPad Pro 12.9 256GB Wi-Fi Silver (MK2L3) 2021",
    price: 1200,
    image: "/Home/ProductList/ipad_pro.png",
    category: "Phones",
    type: "Featured",
    rating: 4,
    stock: 50,
    totalsold: 200,
    discount: 0,
    discountPrice: 1200,
    company: "Apple",
    totalRevenue : 240000,

  },
  {
    id: 10,
    name: "Samsung Galaxy Tab",
    description: "Samsung Galaxy Tab S7 12.4 256GB Wi-Fi Silver",
    price: 600,
    image: "/Home/ProductList/Samsung_Galaxy.png",
    category: "Phones",
    type: "Featured",
    rating: 4,
    stock: 50,
    totalsold: 200,
    discount: 0,
    discountPrice: 600,
    company: "Samsung",
    totalRevenue : 120000,
  },
  {
    id: 11,
    name: "Camera Alpha",
    description: "Sony Alpha Mirrorless Camera with 28-70mm Lens",
    price: 600,
    image: "/Home/ProductList/camera2.png",
    category: "Cameras",
    type: "Bestsellers",
    rating: 4,
    stock: 50,
    totalsold: 200,
    discount: 0,
    discountPrice: 600,
    company: "Sony",
    totalRevenue: 120000,
  },
  {
    id: 12,
    name: "Camera beta",
    description: "Sony beta Mirrorless Camera with 28-70mm Lens",
    price: 600,
    image: "/Home/ProductList/camera3.png",
    category: "Cameras",
    type: "Bestsellers",
    rating: 4,
    stock: 0,
    totalsold: 200,
    discount: 30,
    discountPrice: 420,
    company: "Sony",
    totalRevenue: 84000,
  },
  {
    id: 13,
    name: "Dell XPS 13",
    description: "Dell XPS 13 Laptop with Intel Core i7 Processor",
    price: 1200,
    image: "/Home/ProductList/laptop.png",
    category: "Computers",
    type: "Bestsellers",
    rating: 4,
    stock: 0,
    totalsold: 200,
    discount: 0,
    discountPrice: 1200,
    company: "Dell",
    totalRevenue: 240000,
  },
      {
      id: 14,
      name: "Computer Monitor",
      description :"Dell UltraSharp 27-inch Monitor with 4K Resolution" ,
      price: 600,
      image: "/Home/ProductList/computer1.jpg",
      category: "Computers",
      type: "Bestsellers",
      rating: 4,
      stock: 50,
      totalsold: 200,
      discount: 0,
      discountPrice: 600,
      company: "Dell",
      totalRevenue: 120000,
    },
    {
    id: 15,
    name: "Servillace camera",
    description: "Servillace camera with 28-70mm Lens",
    price: 600,
    image: "/Home/ProductList/camera4.jpg",
    category: "Cameras",
    type: "Bestsellers",
    rating: 4,
    stock: 50,
    totalsold: 200,
    discount: 0,
    discountPrice: 600,
    company: "Servillace",
    totalRevenue: 120000,
  },
  {
    id: 16,
    name: "Game joypad",
    description: "Game joypad with 28-70mm Lens",
    price: 600,
    image: "/Home/ProductList/game1_.jpg",
    category: "Gaming",
    type: "Bestsellers",
    rating: 4,
    stock: 50,
    totalsold: 200,
    discount: 0,
    discountPrice: 600,
    company: "Sony",
    totalRevenue: 120000,
  },
  {
    id: 17,
    name: "Game joystick",
    description: "Game joystick with 28-70mm Lens",
    price: 600,
    image: "/Home/ProductList/game2.jpeg",
    category: "Gaming",
    type: "Bestsellers",
    rating: 4,
    stock: 50,
    totalsold: 200,
    discount: 0,
    discountPrice: 600,
    company: "Sony",
    totalRevenue: 120000,
  },
  {
    id: 18,
    name: "IPhone 14 Pro",
    description: "Apple iPhone 14 Pro 128GB Deep Purple (MK2L3) 2022",
    price: 999,
    image: "/Home/image.png",
    category: "Phones",
    type: "Featured",
    rating: 4,
    stock: 50,
    totalsold: 200,
    discount: 0,
    discountPrice: 999,
    company: "Apple",
    totalRevenue: 199800,
  },
  {
    id: 19,
    name: "Playstation 5",
    description: "Incredibly powerful CPUs, GPUs, and an SSD that changes everything for gaming.",
    price: 600,
    image: "/Home/ssd.png",
    category: "Gaming",
    type: "Bestsellers",
    rating: 4,
    stock: 50,
    totalsold: 200,
    discount: 0,
    discountPrice: 600,
    company: "Sony",
    totalRevenue: 120000,
  },
  {
    id: 20,
    name: "Apple AirPods Max",
    description: "Apple AirPods Max Wireless Headphones with 3D Sound",
    price: 549,
    image: "/Home/headphone.png",
    category: "Headphones",
    type: "Bestsellers",
    rating: 4,
    stock: 50,
    totalsold: 200,
    discount: 0,
    discountPrice: 549,
    company: "Apple",
    totalRevenue: 109800,
  },
  {
    id: 21,
    name: "Apple Vision Pro",
    description: "Apple Vision Pro AR/VR Headset with 3D Sound",
    price: 3499,
    image: "/Home/Apro.png",
    category: "Gaming",
    type: "Featured",
    rating: 4,
    stock: 50,
    totalsold: 200,
    discount: 0,
    discountPrice: 3499,
    company: "Apple",
    totalRevenue: 699800,
  },
  {
    id: 22,
    name: "Macbook Air",
    description: "The new 15-inch MacBook Air makes room for a larger display and more performance, while still being the thinnest and lightest MacBook Air ever.",
    price: 5499,
    image: "/Home/phone_of_section2.png",
    category: "Computers",
    type: "Featured",
    rating: 4,
    stock: 50,
    totalsold: 200,
    discount: 20,
    discountPrice: 4399,
    company: "Apple",
    totalRevenue: 879800,
  },
];


export const homeConfig = {
  heroId: 18,
  featuredIds: [19, 20, 21, 22]
};

